---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    name: postgres
    author: intelliqit
spec:
  replicas: 1
  selector:
    matchLabels:
      name: postgres
  template:
    metadata:
      name: postgres-pod
      labels:
        name: postgres
    spec:
      containers:
        - name: my-postgres
          image: postgres
          env:
            - name: POSTGRES_PASSWORD
              value: intelliqit1
            - name: POSTGRES_USERNAME
              value: myuser
            - name: POSTGRES_DB
              value: mydb
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels:
    author: intelliqit
spec:
  type: ClusterIP
  ports:
    - targetPort: 5432
      port: 5432
  selector:
    name: postgres
...